minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "two-stroke"
  - "jwk-subtle"
  - "pbkdf-subtle"
  - "eslint-config-two-stroke"
trustPolicy: no-downgrade
trustPolicyExclude:
  - "semver@6.3.1"
  - "pino@9.14.0"
ignoreScripts: true
blockExoticSubdeps: true
